#!/usr/bin/env python3
"""Generate the only DUT-specific mapping file for flattened PFE ports."""

from __future__ import annotations

import argparse
from pathlib import Path


def connections(lanes: int) -> list[tuple[str, str]]:
    ports: list[tuple[str, str]] = [("clk", "bus.clk"), ("rst_n", "bus.rst_n")]
    for lane in range(lanes):
        ports.extend(
            [
                (f"lane{lane}_pkt_in_vld", f"bus.pkt_in_vld[{lane}]"),
                (f"lane{lane}_pkt_in_data", f"bus.pkt_in_data[{lane}]"),
                (f"lane{lane}_pkt_in_ctrl", f"bus.pkt_in_ctrl[{lane}]"),
            ]
        )
    ports.append(("pkt_in_bkpr", "bus.pkt_in_bkpr"))
    for lane in range(lanes):
        ports.extend(
            [
                (f"lane{lane}_pkt_out_vld", f"bus.pkt_out_vld[{lane}]"),
                (f"lane{lane}_pkt_out_data", f"bus.pkt_out_data[{lane}]"),
            ]
        )
    for lane in range(lanes):
        ports.extend(
            [
                (f"fwd{lane}_pkt_data_vld", f"bus.fwd_pkt_data_vld[{lane}]"),
                (f"fwd{lane}_pkt_data", f"bus.fwd_pkt_data[{lane}]"),
                (f"fwd{lane}_pkt_lat", f"bus.fwd_pkt_lat[{lane}]"),
                (f"fwd{lane}_pkt_dp_vld", f"bus.fwd_pkt_dp_vld[{lane}]"),
                (f"fwd{lane}_pkt_dp_data", f"bus.fwd_pkt_dp_data[{lane}]"),
            ]
        )
    for lane in range(lanes):
        ports.extend(
            [
                (f"fwded{lane}_pkt_data_vld", f"bus.fwded_pkt_data_vld[{lane}]"),
                (f"fwded{lane}_pkt_data", f"bus.fwded_pkt_data[{lane}]"),
            ]
        )
    return ports


def render(module: str, lanes: int, lane_param: str | None) -> str:
    parameter = f" #(\n  .{lane_param}(LANE_NUM)\n)" if lane_param else ""
    conns = connections(lanes)
    width = max(len(port) for port, _ in conns)
    mapped = []
    for index, (port, signal) in enumerate(conns):
        comma = "," if index != len(conns) - 1 else ""
        mapped.append(f"  .{port:<{width}} ({signal}){comma}")
    return (
        "// Generated by scripts/gen_flat_bind.py. Do not hand-edit.\n"
        f"{module}{parameter} u_dut (\n"
        + "\n".join(mapped)
        + "\n);\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--module", required=True, help="real DUT module name")
    parser.add_argument("--lanes", required=True, type=int, choices=range(3, 8))
    parser.add_argument("--lane-param", default="LANE_NUM")
    parser.add_argument("--no-lane-param", action="store_true")
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    lane_param = None if args.no_lane_param else args.lane_param
    args.output.write_text(render(args.module, args.lanes, lane_param), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
